name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install pandas
          pip install openpyxl
          pip install odfpy

      - name: Build EXE
        run: |
          python build.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ReportGenerator-Windows
          path: dist/*