name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install pandas
          pip install openpyxl
          pip install odfpy

      - name: Build Executable
        run: |
          python build.py

      - name: Create ZIP
        run: |
          powershell Compress-Archive `
            -Path dist\ReportGenerator.exe `
            -DestinationPath ReportGenerator-Windows.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ReportGenerator-Windows
          path: ReportGenerator-Windows.zip